# Generated by Django 3.2.5 on 2021-07-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210708_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='desc',
            new_name='description',
        ),
    ]
