# Generated by Django 3.2.5 on 2021-07-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
    ]
