# Generated by Django 3.2.5 on 2021-07-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210708_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='list_item', to='auctions.Listing'),
        ),
    ]
